# .github/workflows/deploy.yml
name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/n8n-custom:latest .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/n8n-custom:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy n8n-custom \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/n8n-custom:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_ACCESS_TOKEN }},CODE_SANDBOX_ACCESS_TOKEN=${{ secrets.CODE_SANDBOX_ACCESS_TOKEN }},QDRANT_HOST=${{ secrets.QDRANT_HOST }},QDRANT_PORT=${{ secrets.QDRANT_PORT }}
